// functions/scripts/sync-domain.js
// Copies the site's pure domain modules (js/domain/*.js) into
// functions/domain/ so summary.js can import() the same code the browser runs.
// functions/domain/package.json marks the folder as ES modules.
// Run by firebase.json's functions predeploy, or: npm run sync-domain

const fs = require('fs');
const path = require('path');

const from = path.join(__dirname, '..', '..', 'js', 'domain');
const to = path.join(__dirname, '..', 'domain');

fs.mkdirSync(to, { recursive: true });
let n = 0;
for (const file of fs.readdirSync(from)) {
  if (!file.endsWith('.js')) continue;
  fs.copyFileSync(path.join(from, file), path.join(to, file));
  n++;
}
fs.writeFileSync(path.join(to, 'package.json'), JSON.stringify({ type: 'module', private: true }, null, 2) + '\n');
fs.writeFileSync(path.join(to, 'README.txt'), 'Generated by scripts/sync-domain.js from js/domain/. Do not edit here.\n');
console.log(`[sync-domain] copied ${n} files from js/domain to functions/domain`);
